---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: linux
autosplit: true
retryOnFailure: true
maxRetries: 5
concurrency: 2
testDiscovery:
  type: raw
  mode: dynamic
  command: snooper --featureFilePaths=features/ --frameWork=java
testRunnerCommand: bundle exec cucumber "$test" --format html --out cucumber_results.html
pre:
  - bundle install --deployment
cacheKey: '{{ checksum "Gemfile.lock" }}'
cacheDirectories:
  - ./vendor/bundle
uploadArtefacts:
 - name: report
   path:
     - cucumber_results.html
report: true
partialReports:
 location: cucumber_results.html
 type: html
env:
   CONFIG_NAME: "linux"

jobLabel: [selenium-capybara, linux, autosplit]