---
version: "0.1"
matrix:
  os: [win]
  files: ["features/todo1.feature", "features/todo2.feature"]
runson: ${matrix.os}

runtime:
 language: ruby
 version: '3.0.2'

testSuites:
  - bundle exec cucumber "$files" --format html --out cucumber_results.html
pre:
  - bundle install 
cacheKey: '{{ checksum "Gemfile.lock" }}'
cacheDirectories:
  - ./vendor/bundle
uploadArtefacts:
 - name: report
   path:
     - cucumber_results.html
report: true
partialReports:
 location: cucumber_results.html
 type: html

env:
   CONFIG_NAME: "win"

jobLabel: [selenium-capybara, win, matrix]
